import type { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    return {
        imageUrl: img?.imageUrl ?? `https://picsum.photos/seed/${id}/600/400`,
        imageHint: img?.imageHint ?? 'placeholder'
    }
}

export const mockProducts: Omit<Product, 'id'>[] = [
  {
    name: 'Cyber-Quantum Drone',
    category: 'Aerial Tech',
    price: 2499.99,
    viralVelocity: 92,
    status: 'pending',
    ...findImage('prod_1'),
    isHalalCompliant: null,
    complianceReasoning: null,
    seo: null,
  },
  {
    name: 'Neuro-Link AR Glasses',
    category: 'Wearables',
    price: 1200.0,
    viralVelocity: 85,
    status: 'approved',
    ...findImage('prod_2'),
    isHalalCompliant: true,
    complianceReasoning: 'Device contains no biological material and serves a utility purpose.',
    seo: {
      title: 'Neuro-Link AR Glasses: See Your World Differently',
      description: 'Experience the future of augmented reality with the sleek and powerful Neuro-Link AR Glasses.',
      keywords: ['AR', 'augmented reality', 'smart glasses', 'wearable tech'],
    },
  },
  {
    name: 'Bioluminescent Fiber Jacket',
    category: 'Apparel',
    price: 750.5,
    viralVelocity: 78,
    status: 'approved',
    ...findImage('prod_3'),
    isHalalCompliant: true,
    complianceReasoning: 'Materials are synthetic and do not violate any compliance rules.',
    seo: {
      title: 'Glow with the Flow: Bioluminescent Fiber Jacket',
      description: 'Light up the night with this stunning jacket made from next-gen bioluminescent fibers.',
      keywords: ['fashion', 'techwear', 'bioluminescent', 'glowing jacket'],
    },
  },
  {
    name: 'Sentient AI Core',
    category: 'Home AI',
    price: 3500.0,
    viralVelocity: 65,
    status: 'pending',
    ...findImage('prod_4'),
    isHalalCompliant: null,
    complianceReasoning: null,
    seo: null,
  },
  {
    name: 'Auto-Lace Cyber-Kicks',
    category: 'Footwear',
    price: 450.0,
    viralVelocity: 88,
    status: 'rejected',
    ...findImage('prod_5'),
    isHalalCompliant: false,
    complianceReasoning: 'Product contains leather from a non-Zabiha source, rendering it Haram.',
    seo: null,
  },
  {
    name: 'Modular Exo-Pack',
    category: 'Accessories',
    price: 320.75,
    viralVelocity: 72,
    status: 'approved',
    ...findImage('prod_6'),
    isHalalCompliant: true,
    complianceReasoning: 'Utility item made from permissible materials.',
    seo: {
      title: 'Modular Exo-Pack: The Last Backpack You\'ll Ever Need',
      description: 'Customize your carry with the ultra-durable and versatile Modular Exo-Pack.',
      keywords: ['backpack', 'modular', 'tech accessories', 'durable'],
    },
  },
  {
    name: 'Zero-G Planter',
    category: 'Home Decor',
    price: 199.99,
    viralVelocity: 60,
    status: 'pending',
    ...findImage('prod_7'),
    isHalalCompliant: null,
    complianceReasoning: null,
    seo: null,
  },
  {
    name: 'Holo-Phone X',
    category: 'Mobile Devices',
    price: 1899.0,
    viralVelocity: 95,
    status: 'approved',
    ...findImage('prod_8'),
    isHalalCompliant: true,
    complianceReasoning: 'Device contains no biological material and serves a utility purpose.',
    seo: {
      title: 'Holo-Phone X: The Future in Your Hand',
      description: 'Break free from the screen with the revolutionary Holo-Phone X and its holographic interface.',
      keywords: ['smartphone', 'holographic', 'future tech', 'mobile'],
    },
  },
  {
    name: 'Photosynthetic Charger',
    category: 'Gadgets',
    price: 150.0,
    viralVelocity: 81,
    status: 'pending',
    ...findImage('prod_9'),
    isHalalCompliant: null,
    complianceReasoning: null,
    seo: null,
  },
];


export const marketTrendsData = [
  { name: 'Jan', 'Trending Products': 4000, 'Engagement': 2400 },
  { name: 'Feb', 'Trending Products': 3000, 'Engagement': 1398 },
  { name: 'Mar', 'Trending Products': 2000, 'Engagement': 9800 },
  { name: 'Apr', 'Trending Products': 2780, 'Engagement': 3908 },
  { name: 'May', 'Trending Products': 1890, 'Engagement': 4800 },
  { name: 'Jun', 'Trending Products': 2390, 'Engagement': 3800 },
  { name: 'Jul', 'Trending Products': 3490, 'Engagement': 4300 },
];

export const engagementHeatmapData = [
    { hour: '00:00', engagement: 20 },
    { hour: '01:00', engagement: 30 },
    { hour: '02:00', engagement: 40 },
    { hour: '03:00', engagement: 25 },
    { hour: '04:00', engagement: 15 },
    { hour: '05:00', engagement: 35 },
    { hour: '06:00', engagement: 50 },
    { hour: '07:00', engagement: 70 },
    { hour: '08:00', engagement: 90 },
    { hour: '09:00', engagement: 120 },
    { hour: '10:00', engagement: 150 },
    { hour: '11:00', engagement: 180 },
    { hour: '12:00', engagement: 200 },
    { hour: '13:00', engagement: 190 },
    { hour: '14:00', engagement: 170 },
    { hour: '15:00', engagement: 160 },
    { hour: '16:00', engagement: 180 },
    { hour: '17:00', engagement: 220 },
    { hour: '18:00', engagement: 250 },
    { hour: '19:00', engagement: 230 },
    { hour: '20:00', engagement: 210 },
    { hour: '21:00', engagement: 180 },
    { hour: '22:00', engagement: 150 },
    { hour: '23:00', engagement: 100 },
];
